# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.java.home=C:/Program Files/Microsoft/jdk-25.0.4.101-hotspot

# Mod properties
mod_version = 1.0.2+26.3
maven_group = com.dmystery
archives_name = modern_advancements
enabled_platforms = fabric,neoforge

# Minecraft properties
minecraft_version = 26.3

# Dependencies
architectury_api_version = 20.0.12
fabric_loader_version = 0.19.5
fabric_api_version = 0.161.0+26.3
neoforge_version = 26.3.0.21-beta
