modLoader = "javafml"
loaderVersion = "[26,)"
license = "MIT"
issueTrackerURL = "https://github.com/dmystery908-jpg/Modern-Advancements-mod/issues"

[[mods]]
modId = "modern_advancements"
version = "${version}"
displayName = "Modern Advancements"
authors = "dmystery"
description = '''
Client-side UI and quality-of-life overhaul for advancements: fullscreen tree with zoom, interactive criteria inspector, HUD tracking, and progress bars.
'''
logoFile = "assets/modern_advancements/icon.png"

[[dependencies.modern_advancements]]
modId = "neoforge"
type = "required"
versionRange = "[26.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.modern_advancements]]
modId = "minecraft"
type = "required"
versionRange = "[26.1,27.0)"
ordering = "NONE"
side = "BOTH"

[[dependencies.modern_advancements]]
modId = "architectury"
type = "required"
versionRange = "[20.0.12,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "modern_advancements.mixins.json"
